# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4
    working_directory: ~/web
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: sudo npm i -g yarn
      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: bash .circleci/setup-heroku.sh production
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Deploy production to Heroku
          command: git push heroku master
  staging:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Deploy staging to Heroku
          command: git push heroku dev

workflows:
  version: 2
  workflow:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
        - staging:
            requires:
              - build
            filters:
              branches:
                only: dev
