# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/web

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: sudo npm i -g yarn
      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
  deploy:
    docker:
      - image: circleci/node:8.4
    steps:
      - run: echo 'master branch'
  staging:
    docker:
      - image: circleci/node:8.4
    steps:
      - run: echo 'dev branch'

workflows:
  version: 2
  workflow:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
        - staging:
            requires:
              - build
            filters:
              branches:
                only: dev
